apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starai-web
  namespace: starai-mongo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: sg-0392487d8d900d87c
    # Listeners: 80 + 443 on the ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    # ACM cert on the ALB (Venafi-issued)
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:409556437035:certificate/40752bcb-80e5-4a8b-b241-f7a6c8453a8e
    # Redirect HTTP -> HTTPS on ALB
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # Talk HTTPS to pods
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  rules:
    - host: staraimongo.sgcybersec.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starai-web
                port:
                  number: 443
